name: eval and publish notebooks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: docker://esmvfc/esm-vfc-stacks:latest
      options: --user 1001 # https://github.community/t/how-to-run-action-as-a-non-root-user/17572/2
    steps:
      - uses: actions/checkout@v1
      - name: Initialize conda
        run: bash -c "conda init bash"
      - name: Run all notebooks with papermill
        run: |
          bash -c ". ${HOME}/.bashrc && conda activate notebook && .ci/run_all_notebooks.py --dir . --out ci_out/" || echo "failed"
      - name: Convert to HTML
        if: ${{ always() }}
        run: |
          bash -c ". ${HOME}/.bashrc && conda activate notebook && cd ci_out/ && jupyter nbconvert --to HTML \*.ipynb"
      - name: Upload notebook
        uses: actions/upload-artifact@v1
        if: ${{ always() }}
        with:
          name: ci_out
          path: ci_out/
      - name: Prepare pages
        run: |
          mkdir -p ./public
          cp ci_out/*.html ./public/.
          cd ./public && ln -s 03_plot_forecast_data.html index.html
      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
